# Generated by Django 5.1.7 on 2025-03-25 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('address_line1', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('units', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Access_Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_no', models.CharField(max_length=16)),
                ('code', models.CharField(max_length=16)),
                ('type', models.CharField(choices=[('0', 'resident'), ('1', 'invitee')], default='0', max_length=2)),
                ('is_used', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborow.building')),
            ],
        ),
        migrations.CreateModel(
            name='Condition_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Condition_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='condition_photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('condition_log_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_images', to='neighborow.condition_log')),
            ],
        ),
        migrations.CreateModel(
            name='Items_For_Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=2000)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('currently_borrowed', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Items_For_Loan_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('items_for_loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='neighborow.items_for_loan')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32)),
                ('flat_no', models.CharField(max_length=16)),
                ('authorized', models.BooleanField(default=False)),
                ('distance', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('0', 'resident'), ('1', 'invitee')], default='0', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('access_code_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborow.access_code')),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborow.building')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='items_for_loan',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborow.member'),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(default=1)),
                ('relationship', models.CharField(choices=[('0', 'Relative'), ('2', 'Friend'), ('3', 'Neighbour'), ('4', 'Former Resident'), ('5', 'Work colleague'), ('6', 'Other')], default='0', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('access_code_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborow.access_code')),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborow.building')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('invitee_member_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_invitation', to='neighborow.member')),
                ('invitor_member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitation', to='neighborow.member')),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('0', 'built-in messages'), ('1', 'email'), ('2', 'text messages'), ('3', 'WhatsApp')], default='0', max_length=2)),
                ('identification', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborow.member')),
            ],
        ),
        migrations.CreateModel(
            name='Borrowing_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.CharField(max_length=2000)),
                ('required_from', models.DateTimeField(blank=True, null=True)),
                ('required_until', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborow.member')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=175)),
                ('body', models.CharField(max_length=2100)),
                ('message_code', models.CharField(max_length=16)),
                ('inbox', models.BooleanField(default=False)),
                ('outbox', models.BooleanField(default=False)),
                ('internal', models.BooleanField(default=False)),
                ('is_sent_email', models.BooleanField(default=False)),
                ('is_sent_sms', models.BooleanField(default=False)),
                ('is_sent_whatsApp', models.BooleanField(default=True)),
                ('message_type', models.CharField(choices=[('0', 'Undefined'), ('1', 'Other'), ('2', 'Internal'), ('3', 'Borrowing Request'), ('4', 'Reply Inbox/Item List'), ('5', 'Reply Mail'), ('6', 'Incoming SMS'), ('7', 'Free Message'), ('8', 'Reminder')], default='0', max_length=2)),
                ('message_type_id', models.BigIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('receiver_member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_receiver', to='neighborow.member')),
                ('sender_member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to='neighborow.member')),
            ],
        ),
        migrations.CreateModel(
            name='Borrowing_Request_Recipients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('borrowing_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborow.borrowing_request')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborow.member')),
                ('message_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_message', to='neighborow.messages')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_on', models.DateTimeField(blank=True, null=True)),
                ('borrowed_until', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('reminder', models.CharField(choices=[('0', 'Standard'), ('1', 'Reminder 1 Day'), ('2', 'Reminder 2 Hours'), ('3', 'Overdue'), ('4', 'Overdue escalate')], default='0', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('after_condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition_after', to='neighborow.condition_log')),
                ('before_condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition_before', to='neighborow.condition_log')),
                ('borrower_member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to='neighborow.member')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('items_for_loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_item', to='neighborow.items_for_loan')),
                ('lender_member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lender', to='neighborow.member')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('0', 'Invitor distance'), ('1', 'GMX Reply to Mail Processing')], default='0', max_length=2)),
                ('value', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborow.building')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('building_id', 'key'), name='unique_appSettings_building_id_key')],
            },
        ),
        migrations.AddConstraint(
            model_name='access_code',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_access_code_code'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('user_id',), name='unique_Member_user_id'),
        ),
        migrations.AddIndex(
            model_name='items_for_loan',
            index=models.Index(fields=['member_id'], name='neighborow__member__45f2ab_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['invitee_member_id'], name='neighborow__invitee_190836_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['access_code_id'], name='neighborow__access__8b3d9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(fields=('access_code_id',), name='unique_Invitation_access_code_id'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['member_id'], name='neighborow__member__20a57c_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['identification'], name='neighborow__identif_657e69_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowing_request',
            index=models.Index(fields=['member_id'], name='neighborow__member__ed4d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['sender_member_id'], name='neighborow__sender__44916d_idx'),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['receiver_member_id'], name='neighborow__receive_f4fc44_idx'),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['message_code'], name='neighborow__message_77bf04_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowing_request_recipients',
            index=models.Index(fields=['member_id'], name='neighborow__member__81a6bc_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowing_request_recipients',
            index=models.Index(fields=['borrowing_request'], name='neighborow__borrowi_07a82a_idx'),
        ),
        migrations.AddConstraint(
            model_name='borrowing_request_recipients',
            constraint=models.UniqueConstraint(fields=('message_id',), name='unique_borrowing_request_recipients_message_id'),
        ),
        migrations.AddConstraint(
            model_name='borrowing_request_recipients',
            constraint=models.UniqueConstraint(fields=('member_id', 'borrowing_request'), name='unique_borrowing_request_recipients_member_id_borrowing_request_id'),
        ),
    ]
